apiVersion: apps/v1
kind: Deployment
metadata:
  name: formula-app-deployment
  annotations:
    deployment.kubernetes.io/changes-cause: "Initial deployment of the app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: formula-app
  template:
    metadata:
      name: formulal8s
      labels:
        env: "prod"
        app: formula-app
        app.kubernetes.io/name: formula-app
    spec:
      containers:
        - name: formula-app
          image: taylor2512/formuleonel8s:v1
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
---
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  selector:
    app.kubernetes.io/name: formula-app
  ports:
    - name: formula-app
      protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
  
---
 